#!/usr/bin/python3
import sys
import time

f = open(sys.argv[1], "rb")
f.seek(0,2)
while(True):
    time.sleep(0.1)
    inp = f.read()
    if len(inp) > 0:
        #inp = [chr(x) for x in inp]
        for i in range(0, len(inp)):
            print("0x{:02x}  ".format(inp[i]), end="", flush=True)
