export PATH="$PATH:/home/barleto/Apps/Xilin/Vivado/2017.1/bin"
export PATH="$PATH:/home/barleto/Apps/Xilin/SDK/2017.1/bin"
export PATH="$PATH:/opt/mkprom2"
export PATH="$PATH:/opt/sparc-elf-4.4.2/bin"
export PATH="$PATH:/home/barleto/leon3/rcmon"
export PATH="$PATH:/home/barleto/intelFPGA_pro/18.1/modelsim_ase/bin"
export PATH="$PATH:/home/barleto/leon3/hello/rcmon"
export XILINX="/home/barleto/Apps/Xilin/14.7/ISE_DS/ISE"
